# NumPy 

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

  - a powerful N-dimensional array object
  - sophisticated (broadcasting) functions
  - tools for integrating C/C++ and Fortran code
  - useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is licensed under the [BSD](http://www.numpy.org/license.html#license) license, enabling reuse with few restrictions.

## Installation Guide

**It is strongly recommended that you install Python using the Anaconda distribution to make sure all underlying dependencies work with conda install. If you have already installed Anaconda, install NumPy by opening your terminal(for MAC Users) or ANACONDA Command Prompt(for Windows Users) and type the following command - **
    
    conda install numpy
    
**If you are unable to install ANACONDA due to restrictions, please refer to [Numpy's official documentation on installation steps.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy Package

Once NumPy Package is installed successfully, you can import it to the current Python session using the following code:

In [99]:
import numpy as np        # Call the NumPy package using np. notation after executing the same

Numpy has a ton of built-in functions that are useful for Data Scientists & Python Programmers alike.

We shall cover some of the most important topics in Numpy: 

  - Arrays ( using Vectors & Matrices ) 
  - Number Generation Concepts

# Numpy Arrays

NumPy arrays are the one of the most widely used data structuring techniques by Data Scientists. 

Numpy arrays are of two types: Vectors and Matrices. 

Vectors are 1-dimensional arrays and matrices are 2-dimensional arrays(A Matrix can still possess a single row or a column).

We shall begin our learning with how to create NumPy Arrays.

## Creating simple NumPy Array Structures

We could create a simple Array by using a list of values or a list of "List of values".

In [100]:
simple_list = [101,102,103,104,105,106,107,108,109,110]
simple_list

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110]

In [101]:
np.array(simple_list)

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [102]:
simple_list_of_lists = [[10,11,12],[20,21,22],[30,31,32]]
simple_list_of_lists

[[10, 11, 12], [20, 21, 22], [30, 31, 32]]

In [103]:
np.array(simple_list_of_lists)

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

**There are multiple built-in methods to generate Arrays**

### arange

Return evenly spaced values within a given interval as input.

In [104]:
np.arange(0,20)         # Return values 0 to 19. Start value is 0 which is included, the stop value provided is 20 which is not included



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [105]:
np.arange(0,20,4)       # Specify start, stop and step values as input

array([ 0,  4,  8, 12, 16])

### 0's and 1's

Generate arrays of 0's or 1's

In [106]:
np.zeros(10)            # Specify the count of 0's required in the array

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [107]:
np.zeros((4,3))         # Specify the number of rows by columns - 4 rows and 3 cols in this example

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [108]:
np.ones(10)            # Specify the count of 1's required in the array

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [109]:
np.ones((4,5))         # Specify the number of rows by columns - 4 rows and 5 cols in this example

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [110]:
np.linspace(0,20,5)    # Specify the start, stop and number values needed between them. Please note the stop value is also considered in this case



array([  0.,   5.,  10.,  15.,  20.])

In [111]:
np.linspace(0,20,100)

array([  0.        ,   0.2020202 ,   0.4040404 ,   0.60606061,
         0.80808081,   1.01010101,   1.21212121,   1.41414141,
         1.61616162,   1.81818182,   2.02020202,   2.22222222,
         2.42424242,   2.62626263,   2.82828283,   3.03030303,
         3.23232323,   3.43434343,   3.63636364,   3.83838384,
         4.04040404,   4.24242424,   4.44444444,   4.64646465,
         4.84848485,   5.05050505,   5.25252525,   5.45454545,
         5.65656566,   5.85858586,   6.06060606,   6.26262626,
         6.46464646,   6.66666667,   6.86868687,   7.07070707,
         7.27272727,   7.47474747,   7.67676768,   7.87878788,
         8.08080808,   8.28282828,   8.48484848,   8.68686869,
         8.88888889,   9.09090909,   9.29292929,   9.49494949,
         9.6969697 ,   9.8989899 ,  10.1010101 ,  10.3030303 ,
        10.50505051,  10.70707071,  10.90909091,  11.11111111,
        11.31313131,  11.51515152,  11.71717172,  11.91919192,
        12.12121212,  12.32323232,  12.52525253,  12.72

## eye

Return a 2-D array with ones on the diagonal and zeros elsewhere. Also called an identity matrix

In [112]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

## Random 

Numpy has lots of options to create random numbered arrays:

### rand
Create an array of the given shape and populate it with random variables derived from a uniform distribution between `[0, 1)`.

In [113]:
np.random.rand(5)

array([ 0.81515122,  0.87747858,  0.43359386,  0.89360851,  0.69499332])

In [114]:
np.random.rand(3,2)

array([[ 0.64845719,  0.35626761],
       [ 0.42684821,  0.43971294],
       [ 0.84214355,  0.29897879]])

### randn

Return a variable (or a set of variables) from the "Standard Normal" distribution. Unlike rand which is from a uniform distribution: 

A standard Normal Distribution has mean 0 and SD of 1 as we know.

In [115]:
np.random.randn(5)

array([ 0.09539107, -0.51001138, -1.6088154 ,  0.65468843, -0.6414155 ])

In [116]:
np.random.randn(3,2)

array([[ 0.49119209, -0.11877578],
       [ 1.03389759, -0.1953827 ],
       [-0.07014554,  0.3214852 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [117]:
np.random.randint(5,20)       # Returns one rand integer between the values 5 & 19(20 is excluded)

7

In [118]:
np.random.randint(20,50,5)  # Returns  5 rand integers between 20 & 49(50 is excluded)

array([44, 32, 40, 24, 30])

## Array Attributes and Methods for an array

Let us look at some important attributes and methods for an array.

In [119]:
sample_array = np.arange(30)
rand_array = np.random.randint(0,100,20)

In [120]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [121]:
rand_array

array([ 4, 62, 65, 67, 39, 52, 45, 85, 28, 95, 89, 83, 42, 58, 30, 31, 32,
       42, 30, 99])

## Reshape
Returns an array containing the same data with a new shape.

In [122]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [123]:
rand_array

array([ 4, 62, 65, 67, 39, 52, 45, 85, 28, 95, 89, 83, 42, 58, 30, 31, 32,
       42, 30, 99])

In [124]:
rand_array.max()

99

In [125]:
rand_array.argmax()

19

In [126]:
rand_array.min()

4

In [127]:
rand_array.argmin()

0

## Shape

Shape is an attribute that arrays have. It is not a method.

In [128]:
# Vector
sample_array.shape

(30,)

In [129]:
# Output has two sets of brackets - which indicates a matrix and not a vector
sample_array.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [130]:
sample_array.reshape(1,30).shape

(1, 30)

In [131]:
sample_array.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [132]:
sample_array.reshape(30,1).shape

(30, 1)

### dtype

You could retrieve the data type of the object in an array using dtype.

In [133]:
sample_array.dtype

dtype('int64')

In [134]:
sample_array2 = np.random.randn(4,4)

sample_array2

array([[-1.44718165, -0.08449975, -0.34605956,  1.62272219],
       [-0.56372057,  0.84522177,  1.04860736,  0.83893846],
       [ 0.1508341 , -1.25855699,  2.63374759,  1.57901122],
       [ 0.50401999,  0.65827499,  0.10832776,  1.09704721]])

In [135]:
sample_array2.T          # Transpose a matrix

array([[-1.44718165, -0.56372057,  0.1508341 ,  0.50401999],
       [-0.08449975,  0.84522177, -1.25855699,  0.65827499],
       [-0.34605956,  1.04860736,  2.63374759,  0.10832776],
       [ 1.62272219,  0.83893846,  1.57901122,  1.09704721]])

### The END