# NumPy Indexing and Selections

We will now learn how to select objects or groups of objects from an array

In [2]:
import numpy as np

In [12]:
#Create a sample array with 11 values
sample_array = np.arange(10,21)

In [13]:
#Show
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Using brackets for Indexing & Selection


In [14]:
#Get the value at index position 8 from above sample array - Indexing starts from 0 and not 1
sample_array[8]

18

In [15]:
#Get values from a range selection
sample_array[0:3]

array([10, 11, 12])

In [16]:
#Get values from specific index positions
sample_array[[0,4,7]]

array([10, 14, 17])

## Broadcasting

NumPy arrays have the capability of Broadcasting values as seen below

In [19]:
#Setting a fixed value 100 using index range (Broadcasting)
sample_array[1:2]=100

#Show
sample_array

array([ 10, 100,  12,  13,  14,  15,  16,  17,  18,  19,  20])

In [20]:
# Reset array, we shall see the need for reset
sample_array = np.arange(10,21)

#Show
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [21]:
#Subsetting an array
subset_sample_array = sample_array[0:7]

#Output of the subset
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [26]:
#Change the values in the subset
subset_sample_array[:]=1001

#Show subset output again
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# Please Note that the changes in the subset has affected the original sample_array as well

In [27]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

# Data is not copied when we subset, it is a sub-view of the original array 
# This is a feature by default in order to avoid memory problems

In [28]:
#To get a copy, we need to use the copy function
copy_array = sample_array.copy()

copy_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

## Indexing a Matrix - 2 dimensional arrays

The general formats used are 

**sample_matrix[row][col]** 

or

**sample_matrix[row,col]**

We will use the second option as standard.

In [34]:
sample_matrix = np.array(([50,200,5,10],[10,35,50,15],[25,100,145,120],[105,25,65,80]))

#Show output
sample_matrix

array([[ 50, 200,   5,  10],
       [ 10,  35,  50,  15],
       [ 25, 100, 145, 120],
       [105,  25,  65,  80]])

In [35]:
#Indexing rows
sample_matrix[1]


array([10, 35, 50, 15])

In [36]:
# Getting an individual element value from the matrix - Method 1
sample_matrix[1][2]

50

In [38]:
# Getting an individual element value from the matrix - Method 2
sample_matrix[1,2]

50

In [39]:
# Slicing matrix

#Shape (3,3) from top right corner
sample_matrix[:3,1:]

array([[200,   5,  10],
       [ 35,  50,  15],
       [100, 145, 120]])

In [40]:
#Shape bottom row - Extract values from last row only
sample_matrix[3]

array([105,  25,  65,  80])

In [42]:
#Shape bottom row - Including column selection (Alternate to above)
sample_matrix[3,:]

array([105,  25,  65,  80])

### Custom Indexing of Matrix

Custom or Fancy indexing allows you to select entire rows or columns specifically in interest.

In [53]:
#Set up a sample matrix
sample_matrix = np.array(([50,200,5,10,160],[170,10,35,50,15],[125,25,100,145,120],[100,105,25,65,80],[250,15,25,30,100]))

sample_matrix

array([[ 50, 200,   5,  10, 160],
       [170,  10,  35,  50,  15],
       [125,  25, 100, 145, 120],
       [100, 105,  25,  65,  80],
       [250,  15,  25,  30, 100]])

In [51]:
sample_matrix[:,(1,3)]

array([[200,  10],
       [ 10,  50],
       [ 25, 145],
       [105,  65],
       [ 15,  30]])

In [54]:
#Allows to retrieve in any order
sample_matrix[:,(3,1)]

array([[ 10, 200],
       [ 50,  10],
       [145,  25],
       [ 65, 105],
       [ 30,  15]])

## Selection

Using brackets for selection based on operators for comparison

In [57]:
simple_array = np.arange(1,31)
simple_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [59]:
simple_array <10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False], dtype=bool)

In [60]:
boolean_array = simple_array<10

In [61]:
boolean_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False], dtype=bool)

In [63]:
simple_array[boolean_array]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
simple_array[simple_array>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [66]:
a = 11
simple_array[simple_array>a]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30])

## The END