# NumPy Operations

## Arithmetic Operations

In [1]:
import numpy as np
simple_array = np.arange(0,21)

In [2]:
simple_array + simple_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])

In [3]:
simple_array * simple_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400])

In [4]:
simple_array - simple_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# You get a warning message when dividing 0 by 0, and the value is replaced with nan
simple_array/simple_array

/Users/gurumoorthypattabiraman/miniconda3/envs/myenv/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [9]:
# Here, 10/0 is infinity and not nan - You get a warning message along with it
10/simple_array

/Users/gurumoorthypattabiraman/miniconda3/envs/myenv/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([         inf,  10.        ,   5.        ,   3.33333333,
         2.5       ,   2.        ,   1.66666667,   1.42857143,
         1.25      ,   1.11111111,   1.        ,   0.90909091,
         0.83333333,   0.76923077,   0.71428571,   0.66666667,
         0.625     ,   0.58823529,   0.55555556,   0.52631579,   0.5       ])

In [10]:
simple_array**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400])

## Universal Array Functions

Numpy has numerous [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)

They are mathematical operations that can be performed to the entire array

In [11]:
#Calculating Square Root
np.sqrt(simple_array)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595])

In [12]:
#Calclating exponential values (e^)
np.exp(simple_array)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04,   5.98741417e+04,
         1.62754791e+05,   4.42413392e+05,   1.20260428e+06,
         3.26901737e+06,   8.88611052e+06,   2.41549528e+07,
         6.56599691e+07,   1.78482301e+08,   4.85165195e+08])

In [13]:
np.max(simple_array) #Can be found out using simple_array.max() format as well

20

In [41]:
np.argmax(simple_array)  #Gives the index position of max value in the array

20

In [14]:
np.sin(simple_array)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525])

In [15]:
np.log(simple_array)

/Users/gurumoorthypattabiraman/miniconda3/envs/myenv/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509,  2.39789527,  2.48490665,  2.56494936,  2.63905733,
        2.7080502 ,  2.77258872,  2.83321334,  2.89037176,  2.94443898,
        2.99573227])

In [16]:
np.cos(simple_array)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462,
        0.40808206])

In [33]:
np.square(simple_array)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400])

In [23]:
array_2 = np.random.randn(5,5)    #Create a 5x5 matrix with decimal numbers

In [24]:
array_2

array([[ 1.5154873 ,  1.08956852, -1.54677642, -0.33803217,  0.55638121],
       [-0.13041391, -1.81431578,  0.55766679, -0.83713591, -0.92160293],
       [-0.20157085, -1.53429174,  0.88096423, -0.28513422,  0.11524976],
       [-1.59525586, -0.83359155,  1.26604447, -1.29061713, -0.41950168],
       [-1.67383105, -1.10672135,  0.14985956, -0.71509948,  0.70594208]])

In [26]:
np.round(array_2,decimals=2)     #Rounding off the values to 2 decimal places

array([[ 1.52,  1.09, -1.55, -0.34,  0.56],
       [-0.13, -1.81,  0.56, -0.84, -0.92],
       [-0.2 , -1.53,  0.88, -0.29,  0.12],
       [-1.6 , -0.83,  1.27, -1.29, -0.42],
       [-1.67, -1.11,  0.15, -0.72,  0.71]])

In [34]:
np.round(array_2)               #Rounding off values to zero decimal places

array([[ 2.,  1., -2., -0.,  1.],
       [-0., -2.,  1., -1., -1.],
       [-0., -2.,  1., -0.,  0.],
       [-2., -1.,  1., -1., -0.],
       [-2., -1.,  0., -1.,  1.]])

In [36]:
np.std(array_2)                 # Calculate standard deviation

0.97265649451477609

In [37]:
np.var(array_2)                 # Calculate variance

0.94606065632177272

In [39]:
np.mean(array_2)                # Calculate mean

-0.33626912362318351

In [40]:
#Using the unique function
sports = np.array(['Golf', 'Cricket', 'Football', 'Football','Cricket','cricket','Basketball', 'Baseball'])

np.unique(sports)

array(['Baseball', 'Basketball', 'Cricket', 'Football', 'Golf', 'cricket'],
      dtype='<U10')

### Why do we see cricket twice in above output??

In [42]:
# in1d we can test values in one array - returns boolean output
np.in1d(['Fooseball','Cricket','Baseball'],sports)

array([False,  True,  True], dtype=bool)

### The END