## NumPy - Array Input and Output

In [1]:
import numpy as np

In [2]:
#Create a simple array
simple_array = np.arange(11)

simple_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#Save array on hard disk in binary format (file extension is .npy)
np.save('array1',simple_array)

In [4]:
#Change arr
simple_array = np.arange(21)
#Show
simple_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
#Lets see the original saved copy - This does not get affected by the changes we have made to the simple_array
np.load('array1.npy')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#Saving multiple arrays into a zip file using savez (file extension is .npz and not .npy)
np.savez('2_arrays.npz',a=simple_array,b=simple_array)

In [7]:
#Now loading multiple arrays using load
archived_arrays = np.load('2_arrays.npz')

#Show
archived_arrays['a']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
#Saving the arrays as text files

simple_array2 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.savetxt('my_text.txt',simple_array2,delimiter=',')

In [9]:
simple_array2 = np.loadtxt('my_text.txt',delimiter = ',')

simple_array2

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.,  12.,  13.,  14.]])

### The END